# [Task]: T115
# [Spec]: F-010 (US12)
# [Description]: Dapr Kafka pubsub component for Redpanda Cloud
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: todo-app
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    # Redpanda Cloud broker endpoints (comma-separated)
    - name: brokers
      secretKeyRef:
        name: redpanda-credentials
        key: brokers
    # SASL Authentication for Redpanda Cloud
    - name: authType
      value: "password"
    - name: saslUsername
      secretKeyRef:
        name: redpanda-credentials
        key: username
    - name: saslPassword
      secretKeyRef:
        name: redpanda-credentials
        key: password
    - name: saslMechanism
      value: "SCRAM-SHA-256"
    # TLS configuration
    - name: tls
      value: "true"
    - name: skipVerify
      value: "false"
    # Consumer configuration
    - name: consumerGroup
      value: "todo-chatbot"
    - name: initialOffset
      value: "oldest"
    # Producer configuration
    - name: maxMessageBytes
      value: "1048576"  # 1MB
    - name: clientID
      value: "todo-chatbot"
---
# Secret template for Redpanda Cloud credentials
# Create this secret with your actual credentials before deployment:
#   kubectl create secret generic redpanda-credentials \
#     --from-literal=brokers="<broker-url>:9092" \
#     --from-literal=username="<username>" \
#     --from-literal=password="<password>" \
#     -n todo-app
apiVersion: v1
kind: Secret
metadata:
  name: redpanda-credentials-template
  namespace: todo-app
  annotations:
    description: "Template - replace with actual credentials"
type: Opaque
stringData:
  brokers: "your-cluster.cloud.redpanda.com:9092"
  username: "your-username"
  password: "your-password"
