# [Task]: T006
# [Spec]: F-008 (R-008.3)
# [Description]: Dapr Kubernetes secrets store component
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: todo-app
spec:
  type: secretstores.kubernetes
  version: v1
